name: Deployment Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec Alwaysdata
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Copier fichiers et synchroniser dossier flask
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            last_directory=$(basename ${{ github.workspace }})
            cd $HOME/www/
            git clone https://github.com/${{ github.repository }}.git
            if [ "$(ls -A ./flask)" ]; then
              rsync -r ./$last_directory/ ./flask
              rm -rf ./$last_directory
            else
              echo "Le répertoire flask de destination sur votre serveur n'existe pas"
              exit 1
            fi

  Restart:
    needs: Copy
    runs-on: ubuntu-latest
    steps:
      - name: Redémarrer le serveur Flask
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/flask
            # Par exemple, redémarrage via systemctl ou un script perso
            # systemctl restart flask.service
            # ou un script bash
            ./restart.sh
